services:
  mongodb:
    image: mongo:8.0
    container_name: nomnom-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: off

volumes:
  mongodb_data:
